version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    user: root
    ports : 
      - '9090:8080'
    volumes:
      - ./home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # - ../backend/hello/src/main/resources/properties:/var/jenkins_home/workspace/backend_spring/backend/hello/src/main/resources/properties
      # - ../database/env:/var/jenkins_home/workspace/backend_spring/database/env