
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${yml.file.datasource.username}
    url: ${yml.file.datasource.url}
    password: ${yml.file.datasource.password}
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  profiles:
    include: oauth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8000
cloud:
  aws:
    s3:
      bucket: ${yml.file.aws.s3.bucket}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${yml.file.aws.credentials.accessKey}
      secretKey: ${yml.file.aws.credentials.secretKey}